name: Douyin Video Crawler

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨 2 点定时运行爬虫任务
  workflow_dispatch: # 允许手动触发

jobs:
  crawler:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用 Python 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run Douyin crawler
      - name: Run Douyin crawler
        run: |
          python douyin_crawler.py

      # Step 5: Add and commit files if there are changes
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add videos/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add new Douyin videos"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
